name: deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./violet-demo
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: wasm-pack build --release --target web --out-dir public/pkg
      - name: Upload Artefact
        uses: actions/upload-artifact@v2
        with:
          name: demo
          path: ./violet-demo/public
  deploy:
    runs-on: ubuntu-latest
    needs: [demo]
    if: github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Download demo
        uses: actions/download-artifact@v2
        with:
          name: demo
          path: dist/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          exclude_assets: '.github,**/.gitignore'
